API_ID: 10464138
API_HASH: 4185aaae27c0ee23420255f2627ddb5f
BOT_TOKEN: 5547647411:AAEYBceU2y0RuHBFMEcyw2K9WFQNkrw2FUQ


MONGO_URL: mongodb+srv://anonuser:pCuymJvSt77OT3Ic@cluster0.kxrwyuz.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-18174.c275.us-east-1-4.ec2.cloud.redislabs.com
REDIS_PORT: 18174
REDIS_PASS: A9UshnXmWWF3At5i9D00Vd5SjlcZ6zII

SESSION_API_ID: 10464138
SESSION_API_HASH: 4185aaae27c0ee23420255f2627ddb5f
SESSION_STRING: BQDCGSXup6SV4lHII74E5yuoNEihas9wbhqHZKfCpljP9XoXHotx-VG7-KwPWbLMIhfwB46ipHAXXm6euFYN2zxA8QoIuQj9ewraIJZWmr251mNUB7G_S1w5xsK1M64iDyNU5u7Pw4SpQLyt0faYU8KnfPXde-Hr19kglsTqZ-JvsK_yvxoXyNo0gc8AcFl4UNYAo1CXmMBuQCN6XrGuaQ6yJ-RIsQoSs64fJTtiU93VHcAl0HXCWzhLn7pn8-eYIUyeWS2e-5FjpEKX4gnzgbl30PnQSvHBgzT35ymd8px7l6udLRli-49eZ7zrs259qj169tW5cu-7EXBQThmaS4TzAAAAATWyoH4A
ADMINS: 5195866238

OWNER: 5195866238
OWNER: 5195866238
OWNER: 5195866238

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT:  
# LOG_CHAT: 5195866238
LOG_CHAT: 5195866238



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

