API_ID: 10464138
API_HASH: 4185aaae27c0ee23420255f2627ddb5f
BOT_TOKEN: 5547647411:AAEYBceU2y0RuHBFMEcyw2K9WFQNkrw2FUQ


MONGO_URL: mongodb+srv://anonuser:pCuymJvSt77OT3Ic@cluster0.kxrwyuz.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-18174.c275.us-east-1-4.ec2.cloud.redislabs.com
REDIS_PORT: 18174
REDIS_PASS: A9UshnXmWWF3At5i9D00Vd5SjlcZ6zII

SESSION_API_ID: 14440360
SESSION_API_HASH: def0efeb21e9610bcd0b032b2602a400
SESSION_STRING: 1BVtsOHABu1OgXRA5uBXKcDGaudZ0h9CzGAUSDRxDuLX4gnLzsXk8KojlvTS1fOtO7PPYOIT0YQZpBYNlfWIS9e6NMm6-qiEG9ifiMng6NQaLPXQosJO4NIHdbUyrFN6YUKfXnGANn9m3jHoFKVKERJitWkVFE-2Y-9fQyF0SckOcCoN0GFtio9DhLGmRz28QIZbUCSvfs7q1QwH-_uXnmOwQu7gDGl3NGTJQbt7WOBGubehxfM2E-cJAMV-LIJwlRr6tkbD2YqScp8ttwYzai-XS3RVNPLWsqLCdepw6RFgyUi4MCoPKlcspQQfhRFH7jbNNb_hrFU5VQxZB9dN-TyVgmHZesjQ=
ADMINS: 5195866238

OWNER: 5195866238
OWNER: 5195866238
OWNER: 5195866238

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT:  
# LOG_CHAT: 5195866238
LOG_CHAT: 5195866238



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

